name: Format Code

on:
  push:
    paths:
      - 'include/**/*'
      - 'src/**/*'

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Format Code
      run: |
        # Get the list of changed C and header files in the last commit
        files_changed=$(git diff --name-only --cached HEAD~1 | grep -E '\.c$|\.h$')

        # Check if there are any changes
        if [ -n "$files_changed" ]; then
          # Run clang-format on changed files
          clang-format -i -style=file $files_changed

          # Stage changes (this is necessary after modifying files)
          git add $files_changed

          # Commit the changes
          git commit --amend --no-edit
        fi
